### ISSUE TITLE
Fix authentication with Github

### ISSUE THREAD

**Issue by gonzalog** [uqbar-project/mumuki-platform#76]
After clicking on the 'Sign in with Github' link I get this page:
![screenshot from 2015-01-14 16 04 31](https://cloud.githubusercontent.com/assets/4143064/5745509/205188b2-9c08-11e4-8963-76985752eace.png)

**Comment by aguspina** [comment]
This bug was fixed some days ago, please try again and let us know if it still happening.

**Comment by MiguelArrondo** [comment]
Hi, I'm getting the exact same issue when trying to sign in with Github.

**Comment by aguspina** [comment]
Are you trying in mumuki.io or mumuki.herokuapp.com? ?

**Comment by MiguelArrondo** [comment]
I was trying on mumuki.herokuapp.com, I just tried mumuki.io and it worked just fine!

**Comment by flbulgarelli** [comment]
Closing since it couldn't be reproduced
